/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.RASS.model.domain;

import java.io.Serializable;

/**
 * 
 * @author Carri Martin
 *
 */

public class EventBean implements Serializable {

	/**
	 * Autogenerated serialVersionUID from eclipse
	 */
	private static final long serialVersionUID = 1L;

	/** Staff last name */
	private String staffLastName;
	
	/** Staff first name */
        private String staffFirstName;
        
        /** Date */
	private String scheduledDate;
        
        /** Day of the Week */
	private String weekDay;
	
	/** field number */
	private String fieldnumber;
        
	
	public EventBean() {

		/** Default Constructor*/
	}
	
	/**
	 * 
	 * @return the staffFirstName
	 */
	public String getStaffFirstName() {
		return staffFirstName;
	}
	
	/**
	 * 
	 * @param staffFirstName
	 */
	public void setStaffFirstName(String staffFirstName) {
		this.staffFirstName = staffFirstName;
	}
	
        /**
	 * 
	 * @return the staffLastName
	 */
	public String getStaffLastName() {
		return staffLastName;
	}
	
	/**
	 * 
	 * @param staffLastName
	 */
	public void setStaffLastName(String staffLastName) {
		this.staffLastName = staffLastName;
	}
	/**
	 * 
	 * @return the scheduledDate
	 */
	public String getScheduledDate() {
		return scheduledDate;
	}
	
	/**
	 * 
	 * @param scheduledDate
	 */
	public void setScheduledDate(String scheduledDate) {
		this.scheduledDate = scheduledDate;
	}
        
        /**
	 * 
	 * @return the scheduledDate
	 */
	public String getDayofWeek() {
		return weekDay;
	}
	
	/**
	 * 
	 * @param weekDay
	 */
	public void setDayofWeek(String weekDay) {
		this.weekDay = weekDay;
	}
	
	/**
	 * 
	 * @return the membershipNumber
	 */
	public String getFieldNumber() {
		return fieldnumber;
	}
	
	/**
	 * 
	 * @param fieldnumber
	 */
	public void setFieldNumber(String fieldnumber) {
		this.fieldnumber = fieldnumber;
	}
	
}// End AddEvent

